### ISSUE TITLE
rotation

### ISSUE THREAD

**Issue by takov751** [shermp/go-kobo-input#2]
Greetings

I am trying to write my own little app for my kobo reader. However for some reason i just can't find how to rotate 90  all the fonts on print same goes with PrintImage as well. Any idea what am I missing? Or is it in the FBInkConfig i am just blind?

**Comment by takov751** [comment]
There is the FBInkstate and FBInkDump struct , however I can't really edit those values

**Comment by shermp** [comment]
To be honest with you, this was a little experiment that I haven't worked on in a very long time.

It was only ever tested on an Aura H2O, so I'm pretty sure there will be rotation issues on other devices.

Are the problems you are having regarding input rotation? Or display rotation?

**Comment by takov751** [comment]
Display rotation it seems. I even tried with FBink cli failed miserably.
```
[root@(none) gotest]# echo 1 >>/sys/class/graphics/fb0/rotate
[root@(none) gotest]# fbink -x 1 -y 10 "Hello World!"
[FBInk] Detected a Kobo Glo HD (371 => Alyssum @ Mark 6)
[FBInk] Clock tick frequency appears to be 100 Hz
[FBInk] Screen density set to 300 dpi
[FBInk] Variable fb info: 1072x1448, 16bpp @ rotation: 1 (Clockwise, 90°)
[FBInk] Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 6782976 bytes & line length: 2176 bytes
[FBInk] Canonical rotation: 2 (Upside Down, 180°)

```
I am writing a small go application which would communicate with an REST-API. Like a streamdeck, just with kobo. might have to render text as image on api end

**Comment by takov751** [comment]
![image](https://user-images.githubusercontent.com/40316768/141659149-c2db16d8-6c9f-42db-80f3-20e30dd8443b.jpeg)

**Comment by takov751** [comment]
![image](https://user-images.githubusercontent.com/40316768/141659176-905dc3e0-dbe6-4d20-818d-875a4969bcdd.jpeg)

**Comment by takov751** [comment]
I had to bypass fbink go library. Otherwise everything else working.
